language: node_js

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libx11-dev
    - libxkbfile-dev

node_js:
  - "node"

env:
  - CC=gcc-4.8 CXX=g++-4.8

git:
  depth: 10

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - electron-rebuild
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
  - npm run ci
