environment:
  nodejs_version: "6"

platform: x64

image: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

build: off
deploy: off
